### PR TITLE
Title Page

### LINKED ISSUE #2: Title Page
With the implementation of the _JVS 2018_, it would be nice if at a first glance the title pages of theses seemed unified (also, similarity to the Word template). In [this example](https://www.overleaf.com/read/vcsvqjwqbcgj
) is a possible look of the implementation. In fithesis/Change Logs/titlePage-changes.txt, all modified files are listed.
The example does not strictly adhere to the regulations of the Law (PF) and Medical (LF) Faculties, as they want the department name and the programme on the top of the page, but as only a small portion of their students use the LaTeX templates, it is not a major concern.

### PR DESCRIPTION
**Pull request by Witiko**
### Description

I changed the base title page for all the faculties by removing `\thesis@blocks@titlePage@header`, `\thesis@blocks@titlePage@content`, and `\thesis@blocks@titlePage@footer` in `base.dtx` and redefining `\thesis@blocks@titlePage` according to [your Overleaf document][1] and [the Word templates][5].

You may want to see [the example documents][3] produced by [continuous integration][4] and verify that the result looks as expected.

Merging this pull request closes #2.

 [3]: https://github.com/xvrabcov/fithesis/suites/2134072175/artifacts/43614565
 [4]: https://github.com/xvrabcov/fithesis/actions/runs/603603741

### Future work
- [x] I did not add a style for the Faculty of Pharmacy yet. Either we need a separate issue for adding a style for the Faculty of Pharmacy, or I can add it to this pull request before we merge it.
- [x] I did not remove `\thesis@blocks@cover@header`, `\thesis@blocks@cover@content`, or `\thesis@blocks@cover@footer`, and I did not redefine `\thesis@blocks@cover` either. Perhaps we need a separate issue for changing the format of the cover page.
- [x] I did not update the example documents to set the `department` and `field` options using the `\thesisSetup` macro for all faculties that now typeset it on the title page. This should perhaps be added to this pull request before we merge it.
- [x] I did not implement the possibility for the department name and the programme to be displayed on the top of the page for the Faculty of Law and the Faculty of Medicine. These seem quite easy to add using conditional statements, so we should perhaps add them to this pull request before we merge it.
- [x] I did not redefine [the title page for the Faculty of Science][6], which seems to be quite special in that it requires the name of the faculty in Czech. If these are all the changes, then I can add the implementation to this pull request before we merge it. Otherwise, we may need a separate issue for the Faculty of Science.

 [6]: https://is.muni.cz/auth/do/sci/stud/ZP/sablony/sablonaDP-MUNI-SCI.pdf

### How I created this pull request

First, I downloaded fithesis from the remote repository `origin` and I copied branch `master` to `feature/title-page`:

``` bash
$ git clone --origin origin 'git@github.com:xvrabcov/fithesis.git'
$ cd fithesis
$ git checkout master -B feature/title-page
```

Next, I made changes according to #2 and [the Overleaf document][1] and [the Word templates][5].
For every set of changes, I created a separate commit (see the Commits tab on GitHub).

``` bash
$ git add -u
$ git commit -m 'Short description of what I changed (up to 72 characters)'
```

I made seven commits: one for `base.dtx` and one for every faculty that redefines `\thesis@blocks@titlePage` except the Faculty of Science (see section Future work above).

Finally, I pushed the `feature/title-page` to the `origin` remote repository:

``` bash
$ git push origin feature/title-page
```

On GitHub, I opened this pull request:

step-1
step-2

For more information, see [the FI:PB029 materials about working with Git][2].

 [1]: https://www.overleaf.com/read/vcsvqjwqbcgj
 [2]: https://www.fi.muni.cz/lemma/PB029/practices/git/#zaklady
 [5]: https://drive.google.com/drive/u/1/folders/13PtZaBa6wLa3CmB6SYfznBQl9MdZ5AX2

### CODE REVIEW

**Comment by xvrabcov** [comment]
Faculty of Science regulation [from 2019](https://is.muni.cz/auth/do/sci/normy/OD/OD-2019_3/OD_3_2019_-_Pokyny_pro_vypracovani_bc._dipl._a_rigor.praci.pdf) does not specify the language in which the title is written.

**Comment by xvrabcov** [comment]
I have added the `department` and `field` options, among others, into the `\thesisSetup` for each faculty in #11.

**Comment by Witiko** [comment]
> I did not implement the possibility for the department name and the programme to be displayed on the top of the page for the Faculty of Law and the Faculty of Medicine. These seem quite easy to add using conditional statements, so we should perhaps add them to this pull request before we merge it.

Perhaps we could patch `\thesis@blocks@titlePage` from the style files of Law and Medicine using the `\xpathcmd` command from the [regexpatch](https://ctan.org/pkg/regexpatch) package.

> Faculty of Science regulation [from 2019](https://is.muni.cz/auth/do/sci/normy/OD/OD-2019_3/OD_3_2019_-_Pokyny_pro_vypracovani_bc._dipl._a_rigor.praci.pdf) does not specify the language in which the title is written.

It's always nice to delete code.

**Comment by Witiko** [comment]
In 18a3e4a, I have removed most of the changes by Juraj Páleník. After we come to a conclusion about what should happen with `\thesis@blocks@preamble` for the Faculty of Science, the `feature/title-page` branch can be merged with `main`.

**Comment by Witiko** [comment]
@xvrabcov I am merging this PR with the following outstanding issues:

1. I did not remove `\thesis@blocks@cover@header`, `\thesis@blocks@cover@content`, or `\thesis@blocks@cover@footer`, and I did not redefine `\thesis@blocks@cover` either.
2. The `\thesis@blocks@preamble` macro in `sci.dtx` is currently a copypasta from `fi.dtx`, which I am sure is wrong.
3. I did not implement the possibility for the department name and the programme to be displayed on the top of the page for the Faculty of Law and the Faculty of Medicine.

Points 1 and 2 can have their own issues, but I think that point 3 blocks #2 from being closed.

**Pull request merged**
