### PR TITLE
Feature/page numbering

### LINKED ISSUE #45: Page Numbering
Five of the faculties (LAW, MED, SCI, ECON, FSPS) have specified page numbering. It might be better to implement it in accordance with that.

Also, it might be prudent to modify the Number of Pages shown in bibEntry. Currently it does not count pages in preamble into the total number.

### PR DESCRIPTION
**Pull request by Witiko**
Closes #45.

### CODE REVIEW

**Comment by Witiko** [comment]
This PR depends on the fix in #49. Let's merge that first.

**Comment by Witiko** [comment]
ECON is numbered consecutively from the title page (the beginning of the front matter) and the pagination is first shown on the beginning of the introduction (the beginning of the main matter):

econ

**Comment by Witiko** [comment]
FSPS and SCI are numbered consecutively from the title page (the beginning of the front matter) and the pagination is first shown on the beginning of the table of contents:

fsps-sci

**Comment by Witiko** [comment]
LAW and MED are numbered consecutively and shown from the declaration:

law-med

**Review by xvrabcov — APPROVED** [review]
With this PR, the page enumeration now starts at the correct page.

**Pull request merged**
